# ----
# Site

title: CloudCannon
description: CloudCannon has everything you need to build, host and update Jekyll websites.
url: https://cloudcannon.com
disqus_shortname: cloudcannon
baseurl:

google_site_verification: GkBrJRSQqF43wQVGLUeUJFTPBldtIXGCw9toqvS2o_o
permalink: pretty
timezone: Pacific/Auckland
collections:
  case_studies:
    output: false
    permalink: /case-studies/:name/
defaults:
  - scope:
      path: ""
    values:
      header_class: "short"
  - scope:
      path: ""
      type: posts
    values:
      layout: post

# ----------
# SEO plugin

lang: en_NZ
logo: /siteicon.png
twitter:
  username: CloudCannon
facebook:
  publisher: https://www.facebook.com/CloudCannon
social:
  name: CloudCannon
  links:
    - https://twitter.com/CloudCannon
    - https://www.facebook.com/CloudCannon
    - https://plus.google.com/+CloudCannon
    - https://www.youtube.com/c/CloudCannon
    - https://github.com/CloudCannon

exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
