# Site settings
title: International Center for Peace and Integration - ICPI
email: admin@icpi.ge
description: > # this means to ignore newlines until "baseurl:"
  International Center for Peace and Integration
  
url:                https://www.icpi.ge 
baseurl:            https://www.icpi.ge
# the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown


paginate: 3
paginate_path: "blog/page:num"

gems:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
